-- ============================================================================
-- HuellitasEnCasa — sample_data.sql
-- Datos de ejemplo listos para insertar sobre schema.sql. Reproduce fielmente el
-- contenido semilla real que SeedProvider.kt inserta en la app (no es un subconjunto
-- inventado), más un perfil y una mascota de demostración con algo de progreso.
-- ============================================================================

PRAGMA foreign_keys = ON;

-- 1) Especies
INSERT INTO pet_species (id, code, display_name, description, icon_res) VALUES (1, 'PERRO', 'Perro', 'Compañero leal y juguetón. Necesita paseos, ejercicio y mucha compañía.', 'ic_mod_adopcion');
INSERT INTO pet_species (id, code, display_name, description, icon_res) VALUES (2, 'GATO', 'Gato', 'Independiente y curioso. Necesita un espacio propio, arañador y rutina tranquila.', 'ic_mod_adopcion');
INSERT INTO pet_species (id, code, display_name, description, icon_res) VALUES (3, 'CONEJO', 'Conejo', 'Herbívoro sensible. Necesita heno fresco siempre disponible y un espacio seguro.', 'ic_mod_adopcion');
INSERT INTO pet_species (id, code, display_name, description, icon_res) VALUES (4, 'HAMSTER', 'Hámster', 'Pequeño roedor nocturno. Necesita una jaula enriquecida y silencio de día.', 'ic_mod_adopcion');
INSERT INTO pet_species (id, code, display_name, description, icon_res) VALUES (5, 'AVE', 'Ave doméstica', 'Inteligente y sociable. Necesita estímulos, vuelo controlado y una dieta variada.', 'ic_mod_adopcion');

-- 2) Definiciones de necesidad (5 especies x 6 necesidades = 30 filas)
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (1, 1, 'ALIMENTACION', 8, 'Consejo educativo específico de PERRO para ALIMENTACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (2, 1, 'HIDRATACION', 8, 'Consejo educativo específico de PERRO para HIDRATACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (3, 1, 'HIGIENE', 8, 'Consejo educativo específico de PERRO para HIGIENE.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (4, 1, 'ACTIVIDAD', 8, 'Consejo educativo específico de PERRO para ACTIVIDAD.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (5, 1, 'DESCANSO', 8, 'Consejo educativo específico de PERRO para DESCANSO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (6, 1, 'AFECTO', 8, 'Consejo educativo específico de PERRO para AFECTO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (7, 2, 'ALIMENTACION', 8, 'Consejo educativo específico de GATO para ALIMENTACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (8, 2, 'HIDRATACION', 8, 'Consejo educativo específico de GATO para HIDRATACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (9, 2, 'HIGIENE', 8, 'Consejo educativo específico de GATO para HIGIENE.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (10, 2, 'ACTIVIDAD', 8, 'Consejo educativo específico de GATO para ACTIVIDAD.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (11, 2, 'DESCANSO', 8, 'Consejo educativo específico de GATO para DESCANSO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (12, 2, 'AFECTO', 8, 'Consejo educativo específico de GATO para AFECTO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (13, 3, 'ALIMENTACION', 8, 'Consejo educativo específico de CONEJO para ALIMENTACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (14, 3, 'HIDRATACION', 8, 'Consejo educativo específico de CONEJO para HIDRATACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (15, 3, 'HIGIENE', 8, 'Consejo educativo específico de CONEJO para HIGIENE.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (16, 3, 'ACTIVIDAD', 8, 'Consejo educativo específico de CONEJO para ACTIVIDAD.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (17, 3, 'DESCANSO', 8, 'Consejo educativo específico de CONEJO para DESCANSO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (18, 3, 'AFECTO', 8, 'Consejo educativo específico de CONEJO para AFECTO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (19, 4, 'ALIMENTACION', 8, 'Consejo educativo específico de HAMSTER para ALIMENTACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (20, 4, 'HIDRATACION', 8, 'Consejo educativo específico de HAMSTER para HIDRATACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (21, 4, 'HIGIENE', 8, 'Consejo educativo específico de HAMSTER para HIGIENE.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (22, 4, 'ACTIVIDAD', 8, 'Consejo educativo específico de HAMSTER para ACTIVIDAD.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (23, 4, 'DESCANSO', 8, 'Consejo educativo específico de HAMSTER para DESCANSO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (24, 4, 'AFECTO', 8, 'Consejo educativo específico de HAMSTER para AFECTO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (25, 5, 'ALIMENTACION', 8, 'Consejo educativo específico de AVE para ALIMENTACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (26, 5, 'HIDRATACION', 8, 'Consejo educativo específico de AVE para HIDRATACION.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (27, 5, 'HIGIENE', 8, 'Consejo educativo específico de AVE para HIGIENE.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (28, 5, 'ACTIVIDAD', 8, 'Consejo educativo específico de AVE para ACTIVIDAD.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (29, 5, 'DESCANSO', 8, 'Consejo educativo específico de AVE para DESCANSO.');
INSERT INTO pet_need_definitions (id, species_id, need_type, session_decay, care_tip) VALUES (30, 5, 'AFECTO', 8, 'Consejo educativo específico de AVE para AFECTO.');

-- 3) Objetos del hogar (8 filas)
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (1, 'CUENCO_COMIDA', 'Cuenco de comida', 'item_cuenco_comida', 'Debe estar limpio y con la ración adecuada para cada especie.', 'PERRO,GATO,CONEJO,HAMSTER,AVE');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (2, 'CUENCO_AGUA', 'Cuenco de agua fresca', 'item_cuenco_agua', 'El agua limpia debe estar siempre disponible, cerca pero no encima de la comida.', 'PERRO,GATO,CONEJO,HAMSTER,AVE');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (3, 'CAMA', 'Cama o nido acogedor', 'item_cama', 'Un lugar suave y tranquilo donde la mascota pueda descansar sin ser molestada.', 'PERRO,GATO,CONEJO');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (4, 'JUGUETE', 'Pelota de juego', 'item_juguete_pelota', 'Estimula el juego activo y ayuda a gastar energía de forma divertida.', 'PERRO,GATO');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (5, 'HIGIENE', 'Cepillo de aseo', 'item_cepillo', 'Ayuda a mantener el pelaje limpio y sin nudos; también fortalece el vínculo.', 'PERRO,GATO,CONEJO');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (6, 'ENTORNO', 'Correa para paseo', 'item_correa', 'Necesaria para pasear de forma segura fuera de casa.', 'PERRO');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (7, 'ENTORNO', 'Planta segura de interior', 'item_planta_interior', 'Decora el espacio; siempre debe verificarse que no sea tóxica para la mascota.', 'GATO,CONEJO,AVE');
INSERT INTO home_items (id, category, name, icon_res, description, compatible_species_csv) VALUES (8, 'ENTORNO', 'Ventana con luz natural', 'item_ventana_luz', 'La luz natural regula el ritmo de sueño y actividad de la mascota.', 'PERRO,GATO,CONEJO,HAMSTER,AVE');

-- 4) Insignias (10 filas)
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (1, 'PRIMERA_ADOPCION', 'Primera adopción', 'Adoptaste a tu primera mascota virtual.', 'badge_primera_adopcion', 1);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (2, 'MAESTRO_COMIDAS', 'Maestro de comidas', 'Clasificaste correctamente 15 tarjetas de alimentos.', 'badge_maestro_comidas', 1);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (3, 'HIGIENE_EXPERTA', 'Higiene experta', 'Realizaste 10 acciones de higiene con tu mascota.', 'badge_higiene_experta', 1);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (4, 'ENERGIA_ACTIVA', 'Energía activa', 'Completaste 10 actividades de juego o paseo.', 'badge_energia_activa', 1);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (5, 'GUARDIAN_BIENESTAR', 'Guardián del bienestar', 'Respondiste correctamente 10 escenarios de bienestar.', 'badge_guardian_bienestar', 2);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (6, 'PLANIFICADOR', 'Planificador experto', 'Completaste 5 planes diarios de cuidado.', 'badge_planificador', 2);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (7, 'ACADEMIA_ORO', 'Academia de oro', 'Terminaste todas las lecciones de la Academia de cuidado.', 'badge_academia_oro', 2);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (8, 'AMIGO_FIEL', 'Amigo fiel', 'Cuidaste a tu mascota durante 7 sesiones distintas.', 'badge_amigo_fiel', 2);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (9, 'VETERINARIO_JUNIOR', 'Veterinario junior', 'Respondiste correctamente 20 escenarios de bienestar en total.', 'badge_veterinario_junior', 3);
INSERT INTO badges (id, code, name, description, icon_res, tier) VALUES (10, 'DECORADOR', 'Decorador de hogares', 'Desbloqueaste 5 decoraciones distintas para el hogar.', 'badge_decorador', 3);

-- 5) Decoraciones (8 filas)
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (1, 'MACETA_FLORES', 'Maceta con flores', 'decor_maceta_flores', 'JARDIN');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (2, 'COJIN_ESTRELLA', 'Cojín con estrella', 'decor_cojin_estrella', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (3, 'LAMPARA_LUNA', 'Lámpara de luna', 'decor_lampara_luna', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (4, 'ALFOMBRA_RAYAS', 'Alfombra a rayas', 'decor_alfombra_rayas', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (5, 'CUADRO_PAISAJE', 'Cuadro de paisaje', 'decor_cuadro_paisaje', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (6, 'MANTA_CUADROS', 'Manta a cuadros', 'decor_manta_cuadros', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (7, 'ESTANTERIA_LIBROS', 'Estantería con libros', 'decor_estanteria_libros', 'HOGAR');
INSERT INTO decorations (id, code, name, icon_res, category) VALUES (8, 'FAROLILLO', 'Farolillo de jardín', 'decor_farolillo', 'JARDIN');

-- 6) Alimentos / situaciones (50 filas)
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (1, 1, 'Croquetas para perro', 'ALIMENTO_BUENO', 'food_pienso', 1, 'El pienso balanceado aporta todos los nutrientes que un perro adulto necesita.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (2, NULL, 'Zanahoria en trozos', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'La zanahoria es un snack crujiente, bajo en calorías y rico en fibra para perros y conejos.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (3, NULL, 'Pollo cocido sin hueso', 'ALIMENTO_BUENO', 'food_carne_pescado', 1, 'El pollo cocido, sin piel ni huesos, es una fuente segura de proteína para perros y gatos.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (4, 2, 'Croquetas para gato', 'ALIMENTO_BUENO', 'food_pienso', 1, 'El pienso específico para gatos contiene taurina, un nutriente esencial que ellos necesitan.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (5, 2, 'Atún en agua (poca cantidad)', 'ALIMENTO_BUENO', 'food_carne_pescado', 1, 'En cantidades pequeñas y ocasionales, el atún natural puede ser un premio para gatos.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (6, 3, 'Heno fresco', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'El heno debe estar siempre disponible: ayuda a la digestión y desgasta los dientes del conejo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (7, 3, 'Hojas de lechuga romana', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'En pequeñas cantidades, la lechuga romana es segura y refrescante para el conejo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (8, 4, 'Mezcla de semillas para hámster', 'ALIMENTO_BUENO', 'food_pienso', 1, 'Una mezcla equilibrada de semillas es la base de la dieta de un hámster.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (9, NULL, 'Trocito de manzana sin semillas', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'La manzana sin semillas es un premio ocasional seguro para hámsters y aves.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (10, 5, 'Mezcla de semillas para ave', 'ALIMENTO_BUENO', 'food_pienso', 1, 'La mezcla de semillas específica cubre las necesidades energéticas del ave.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (11, 5, 'Brócoli al vapor en trocitos', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'El brócoli cocido y en trozos pequeños aporta vitaminas sin dañar al ave.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (12, NULL, 'Agua fresca y limpia', 'ALIMENTO_BUENO', 'food_agua_fresca', 1, 'El agua limpia y renovada a diario es esencial para todas las especies.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (13, 3, 'Pepino en rodajas', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'El pepino hidrata y es un snack ligero apto para conejos y cobayas.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (14, 1, 'Calabacín cocido', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'El calabacín cocido en trozos pequeños es suave para el estómago del perro.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (15, NULL, 'Arándanos frescos', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'Los arándanos son un premio saludable y antioxidante para perros y aves.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (16, 2, 'Sardina cocida sin sal', 'ALIMENTO_BUENO', 'food_carne_pescado', 1, 'El pescado azul sin sal aporta ácidos grasos beneficiosos para el gato.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (17, 4, 'Pipas de girasol (con moderación)', 'ALIMENTO_BUENO', 'food_pienso', 1, 'En pequeñas cantidades, las pipas sin sal son un premio energético para el hámster.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (18, 3, 'Espinaca cruda en poca cantidad', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'Ofrecida con moderación, la espinaca aporta hierro al conejo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (19, 1, 'Huevo cocido (poca cantidad)', 'ALIMENTO_BUENO', 'food_carne_pescado', 1, 'El huevo bien cocido, sin sal, es una fuente ocasional de proteína para el perro.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (20, NULL, 'Fresas en trozos pequeños', 'ALIMENTO_BUENO', 'food_fruta_verdura', 1, 'Las fresas son un premio dulce y natural, seguro con moderación.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (21, NULL, 'Chocolate', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'El chocolate contiene teobromina, una sustancia tóxica y peligrosa para perros y gatos.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (22, NULL, 'Uvas y pasas', 'ALIMENTO_MALO', 'food_fruta_verdura', 0, 'Las uvas y pasas pueden dañar gravemente los riñones de un perro, aunque parezcan inofensivas.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (23, NULL, 'Cebolla y ajo', 'ALIMENTO_MALO', 'food_planta_toxica', 0, 'La cebolla y el ajo dañan los glóbulos rojos de perros y gatos, incluso cocinados.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (24, NULL, 'Huesos de pollo cocidos', 'ALIMENTO_MALO', 'food_hueso_prohibido', 0, 'Los huesos cocidos se astillan fácilmente y pueden herir el interior del perro.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (25, NULL, 'Leche de vaca', 'ALIMENTO_MALO', 'food_lacteo', 0, 'Muchos gatos y perros adultos no digieren bien la lactosa; puede causarles malestar.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (26, 5, 'Aguacate', 'ALIMENTO_MALO', 'food_planta_toxica', 0, 'El aguacate contiene persina, una sustancia tóxica sobre todo para aves.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (27, NULL, 'Caramelos y golosinas', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'El azúcar y los edulcorantes artificiales pueden ser tóxicos y dañar los dientes.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (28, NULL, 'Café o bebidas con cafeína', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'La cafeína acelera peligrosamente el corazón de perros y gatos, incluso en pequeñas dosis.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (29, 3, 'Lechuga iceberg en exceso', 'ALIMENTO_MALO', 'food_fruta_verdura', 0, 'En exceso aporta poca fibra y puede causar diarrea en el conejo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (30, NULL, 'Comida frita o con mucha sal', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'La comida grasa o salada puede dañar el estómago y el corazón de la mascota.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (31, 3, 'Ruibarbo y sus hojas', 'ALIMENTO_MALO', 'food_planta_toxica', 0, 'Las hojas de ruibarbo son tóxicas para conejos y otros pequeños mamíferos.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (32, NULL, 'Semillas de manzana', 'ALIMENTO_MALO', 'food_planta_toxica', 0, 'Las semillas de manzana contienen una sustancia tóxica; solo la pulpa es segura.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (33, 4, 'Cítricos (naranja, limón)', 'ALIMENTO_MALO', 'food_fruta_verdura', 0, 'Los cítricos pueden irritar el estómago del hámster y de las aves.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (34, 1, 'Xilitol (chicles sin azúcar)', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'El xilitol es un edulcorante muy tóxico incluso en cantidades mínimas para el perro.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (35, 3, 'Perejil en grandes cantidades', 'ALIMENTO_MALO', 'food_fruta_verdura', 0, 'En grandes cantidades puede afectar los riñones del conejo; solo en pequeñas porciones.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (36, NULL, 'Dejar agua estancada varios días', 'SITUACION', 'food_agua_fresca', 0, 'El agua debe cambiarse todos los días; el agua estancada acumula bacterias.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (37, NULL, 'Cambiar el agua todos los días', 'SITUACION', 'food_agua_fresca', 1, 'Renovar el agua a diario mantiene a la mascota hidratada y sana.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (38, 4, 'Bañar al hámster con agua', 'SITUACION', 'food_agua_fresca', 0, 'Los hámsters se asean solos; bañarlos con agua puede enfermarlos por el frío.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (39, 4, 'Ofrecer un baño de arena al hámster', 'SITUACION', 'food_pienso', 1, 'Un baño de arena especial permite al hámster limpiarse de forma natural y segura.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (40, 1, 'Dejar al perro sin paseo varios días', 'SITUACION', 'food_hueso_prohibido', 0, 'El perro necesita salir a pasear a diario para su salud física y mental.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (41, 1, 'Sacar a pasear al perro cada día', 'SITUACION', 'food_hueso_prohibido', 1, 'El paseo diario cubre su necesidad de actividad y de explorar el entorno.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (42, NULL, 'Limpiar la jaula solo una vez al mes', 'SITUACION', 'food_pienso', 0, 'La jaula debe limpiarse con frecuencia para evitar malos olores y enfermedades.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (43, NULL, 'Limpiar la jaula o el espacio cada semana', 'SITUACION', 'food_pienso', 1, 'Una limpieza regular mantiene el espacio de la mascota sano y cómodo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (44, NULL, 'Dejar comida sin terminar varios días en el plato', 'SITUACION', 'food_pienso', 0, 'La comida que se echa a perder debe retirarse para que no enferme a la mascota.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (45, 3, 'Ofrecer heno fresco cada día al conejo', 'SITUACION', 'food_fruta_verdura', 1, 'Renovar el heno a diario asegura que el conejo siempre tenga fibra fresca.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (46, 5, 'Dejar al ave sin salir nunca de la jaula', 'SITUACION', 'food_pienso', 0, 'El ave necesita tiempo fuera de la jaula, en un espacio seguro, para volar y estirar las alas.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (47, 5, 'Dejar salir al ave a un espacio seguro y supervisado', 'SITUACION', 'food_pienso', 1, 'El tiempo de vuelo supervisado es clave para el bienestar físico del ave.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (48, 1, 'Cepillar al perro de pelo largo cada semana', 'SITUACION', 'food_pienso', 1, 'El cepillado regular evita nudos y ayuda a detectar heridas o parásitos a tiempo.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (49, 4, 'No cambiar nunca el sustrato del hámster', 'SITUACION', 'food_pienso', 0, 'Un sustrato sucio genera humedad y malos olores que afectan la salud del hámster.');
INSERT INTO food_items (id, species_id, name, category, icon_res, is_appropriate, explanation) VALUES (50, NULL, 'Chocolate con leche como premio', 'ALIMENTO_MALO', 'food_dulce_prohibido', 0, 'Ningún tipo de chocolate es seguro para mascotas, ni siquiera en pequeñas cantidades.');

-- 7) Escenarios de bienestar (30 filas)
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (1, 1, 'Tu perro se rasca mucho la oreja y la sacude todo el tiempo.', 'ic_mod_bienestar', 'Ignorarlo, seguro se le pasa solo|Revisar con cuidado y avisar a un adulto o al veterinario|Ponerle un perfume para que huela mejor', 1, 'Rascarse mucho la oreja puede indicar una infección o un objeto molestándole; conviene que un adulto lo revise.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (2, 1, 'Después de pasear, tu perro jadea mucho y busca la sombra.', 'ic_mod_bienestar', 'Dejarlo descansar y ofrecerle agua fresca|Obligarlo a seguir jugando|Darle chocolate para animarlo', 0, 'Jadear y buscar sombra es normal tras el ejercicio: necesita descanso y agua fresca.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (3, 1, 'Tu perro no ha tocado su comida en todo el día y está decaído.', 'ic_mod_bienestar', 'Esperar una semana a ver qué pasa|Registrar la situación y comentarlo con un adulto o veterinario|Cambiarle la comida por chocolate', 1, 'No comer durante un día entero junto con decaimiento merece atención de un adulto o veterinario.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (4, 1, 'Ves que tu perro mueve la cola y trae su juguete favorito.', 'ic_mod_bienestar', 'Jugar un rato con él|Ignorarlo por completo|Regañarlo sin motivo', 0, 'Traer el juguete y mover la cola son señales de que quiere jugar; responder fortalece el vínculo.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (5, 1, 'Hace mucho calor y vas a dejar a tu perro en el jardín todo el día.', 'ic_mod_bienestar', 'Dejarlo sin sombra ni agua|Asegurarte de que tenga sombra y agua fresca disponible|Ponerle un abrigo', 1, 'En días de calor, la sombra y el agua fresca son esenciales para evitar un golpe de calor.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (6, 1, 'Tu perro tiembla, se esconde y no quiere salir durante una tormenta.', 'ic_mod_bienestar', 'Forzarlo a salir igualmente|Dejarle un lugar tranquilo y acompañarlo con calma|Dejarlo solo y cerrar la puerta', 1, 'El miedo a los truenos es común; ofrecer calma y un refugio tranquilo ayuda a que se sienta seguro.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (7, 2, 'Tu gato se esconde debajo de la cama y no quiere salir en todo el día.', 'ic_mod_bienestar', 'Sacarlo a la fuerza|Dejarle espacio y observar si vuelve a comer y jugar con normalidad|Ignorarlo una semana entera', 1, 'Esconderse un rato es normal en gatos, pero si persiste conviene observarlo y, si sigue, avisar a un adulto.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (8, 2, 'Notas que tu gato vomita una bola de pelo de vez en cuando.', 'ic_mod_bienestar', 'Es normal ocasionalmente; puedes cepillarlo más seguido|Alarmarse y dejar de alimentarlo|Bañarlo inmediatamente', 0, 'Las bolas de pelo ocasionales son comunes; cepillarlo con más frecuencia reduce su formación.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (9, 2, 'Tu gato araña el sofá en vez del rascador.', 'ic_mod_bienestar', 'Regañarlo fuerte y encerrarlo|Colocar el rascador cerca del sofá y premiarlo cuando lo use|Quitarle todas las uñas', 1, 'Redirigir el comportamiento hacia el rascador con paciencia y premios funciona mejor que el castigo.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (10, 2, 'Tu gato maúlla mucho y no se acerca al plato de agua.', 'ic_mod_bienestar', 'Cambiar el agua de lugar, lejos de la comida, y ofrecer agua fresca|No hacer nada|Darle solo leche de vaca', 0, 'Muchos gatos prefieren el agua lejos de la comida; renovarla puede animarlo a beber más.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (11, 2, 'Tu gato deja de usar la caja de arena y hace sus necesidades fuera.', 'ic_mod_bienestar', 'Castigarlo|Revisar que la arena esté limpia y, si continúa, avisar a un adulto|Cambiarlo de casa', 1, 'Este cambio de conducta puede indicar estrés o un problema de salud; conviene revisarlo con un adulto.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (12, 2, 'Ves que tu gato duerme casi todo el día.', 'ic_mod_bienestar', 'Preocuparte, es raro que duerma tanto|Es normal: los gatos duermen muchas horas al día|Despertarlo cada hora', 1, 'Dormir gran parte del día es completamente normal en la conducta felina.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (13, 3, 'Notas que tu conejo no ha comido heno en todo el día.', 'ic_mod_bienestar', 'Esperar sin hacer nada|Avisar a un adulto: en conejos, dejar de comer es una señal urgente|Darle solo golosinas dulces', 1, 'En conejos, dejar de comer incluso pocas horas puede ser grave y requiere atención rápida de un adulto.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (14, 3, 'Tu conejo golpea el suelo con la pata trasera de repente.', 'ic_mod_bienestar', 'Ignorarlo|Revisar el entorno: puede estar advirtiendo de algo que le asusta|Regañarlo', 1, 'Golpear el suelo es una señal de alerta o alarma; conviene revisar si algo lo está asustando.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (15, 3, 'Ves que tu conejo se estira relajado y mordisquea despacio el heno.', 'ic_mod_bienestar', 'Dejarlo tranquilo, está cómodo y relajado|Molestarlo para que se mueva|Sacarlo de su espacio a la fuerza', 0, 'Un conejo relajado que come con calma está mostrando bienestar; lo mejor es no interrumpirlo.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (16, 3, 'Su jaula lleva dos semanas sin limpiarse y huele fuerte.', 'ic_mod_bienestar', 'Dejarla así, no pasa nada|Limpiarla esta misma semana con ayuda de un adulto|Rociar perfume para tapar el olor', 1, 'Un espacio limpio y seco es esencial para evitar enfermedades respiratorias y de piel.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (17, 3, 'Tu conejo se deja acariciar la cabeza pero se aparta si tocas su lomo.', 'ic_mod_bienestar', 'Respetar su límite y acariciar solo donde está cómodo|Forzarlo a que se deje tocar en todas partes|Dejar de acariciarlo para siempre', 0, 'Respetar las zonas donde el conejo se siente cómodo construye confianza poco a poco.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (18, 3, 'Hace mucho calor y el conejo está tumbado sin moverse, respirando rápido.', 'ic_mod_bienestar', 'Dejarlo al sol para que se caliente más|Llevarlo a la sombra, ofrecer agua fresca y avisar a un adulto|No hacer nada', 1, 'Los conejos son muy sensibles al calor; respirar rápido y estar inmóvil puede indicar un golpe de calor.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (19, 4, 'Tu hámster está muy quieto durante el día y no se mueve.', 'ic_mod_bienestar', 'Despertarlo para jugar|Dejarlo dormir: es un animal nocturno y de día suele descansar|Sacarlo de la jaula y sacudirlo', 1, 'Los hámsters son nocturnos; estar quietos de día es su comportamiento normal, no una señal de alarma.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (20, 4, 'Ves que tu hámster guarda comida en las mejillas y la esconde en un rincón.', 'ic_mod_bienestar', 'Es un comportamiento normal de acumulación, no hace falta hacer nada especial|Regañarlo por no comer|Quitarle toda la comida guardada', 0, 'Guardar comida en los carrillos y acumularla es un comportamiento natural del hámster.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (21, 4, 'La rueda de ejercicio de tu hámster hace un ruido chirriante constante.', 'ic_mod_bienestar', 'Ignorarlo, no afecta al hámster|Revisarla y limpiarla o engrasarla con ayuda de un adulto|Quitarle la rueda para siempre', 1, 'Una rueda que chirría puede indicar que necesita mantenimiento; además el ruido puede estresarlo.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (22, 4, 'Notas que tu hámster ha perdido pelo en una zona y se rasca mucho ahí.', 'ic_mod_bienestar', 'No darle importancia|Comentarlo con un adulto para que revise si necesita veterinario|Cortarle el pelo restante', 1, 'La pérdida de pelo localizada junto con rascado puede indicar un problema de piel a revisar.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (23, 4, 'Vas a manipular a tu hámster por primera vez en el día.', 'ic_mod_bienestar', 'Agarrarlo rápido y por la cola|Dejar que huela tu mano primero y luego tomarlo con ambas manos, con calma|Levantarlo de golpe mientras duerme', 1, 'Acercarse con calma y dejar que reconozca tu mano evita sustos y mordiscos.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (24, 4, 'El bebedero de tu hámster está vacío desde ayer.', 'ic_mod_bienestar', 'Rellenarlo cuanto antes con agua limpia|Esperar al día siguiente|Darle solo fruta en su lugar', 0, 'El agua no debe faltar nunca; hay que rellenarla en cuanto se detecta que está vacía.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (25, 5, 'Tu ave se arranca plumas del pecho repetidamente.', 'ic_mod_bienestar', 'Ignorarlo, las plumas vuelven a crecer solas siempre|Comentarlo con un adulto: puede ser estrés o aburrimiento|Cubrir la jaula todo el día', 1, 'Arrancarse plumas suele indicar estrés, aburrimiento o un problema de salud; conviene consultarlo.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (26, 5, 'Ves que tu ave canta y salta activamente en su percha por la mañana.', 'ic_mod_bienestar', 'Es una señal de que está contenta y en buen estado|Es preocupante y hay que llevarla al veterinario ya|Hay que hacerla callar', 0, 'Cantar y moverse con energía por la mañana es una señal típica de bienestar en muchas aves.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (27, 5, 'Tu ave está erizada, con los ojos entrecerrados y no come.', 'ic_mod_bienestar', 'Esperar unos días a ver si mejora sola|Avisar a un adulto pronto: puede ser un signo de enfermedad|Darle solo agua con azúcar', 1, 'Un ave enferma suele esconder los síntomas; estar erizada y sin comer es señal de alarma que requiere atención pronto.', 1);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (28, 5, 'Vas a limpiar el bebedero y el comedero del ave.', 'ic_mod_bienestar', 'Lavarlos con agua y dejar todo limpio y seco antes de rellenar|Rellenar directamente sin lavar|Usar detergente fuerte sin enjuagar', 0, 'Lavar bien los recipientes evita bacterias y mantiene la comida y el agua en buen estado.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (29, 5, 'El ave lleva todo el día en la jaula sin salir a volar.', 'ic_mod_bienestar', 'Está bien así siempre|Ofrecerle un rato de vuelo supervisado en un espacio seguro|Dejarla encerrada una semana más', 1, 'El tiempo de vuelo supervisado es importante para su salud física y mental.', 0);
INSERT INTO wellbeing_scenarios (id, species_id, situation_text, icon_res, options_csv, correct_option_index, explanation, recommend_ask_adult) VALUES (30, 5, 'Notas que el ave se acerca a los barrotes cuando te ve llegar.', 'ic_mod_bienestar', 'Ignorarla y alejarte|Saludarla con calma y ofrecerle un momento de atención|Golpear la jaula para jugar', 1, 'Acercarse a saludar es una señal de vínculo positivo; responder con calma refuerza esa confianza.', 0);

-- 8) Misiones (30 filas, con recompensas reales resueltas)
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (1, 'M_ADOPTAR_PRIMERA', 'Tu primera mascota', 'Adopta a tu primera mascota virtual en el centro de adopción.', 'ADOPCION', 1, 1, NULL, 0, 'ic_mod_adopcion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (2, 'M_ADOPTAR_SEGUNDA', 'Un nuevo amigo', 'Adopta a una segunda mascota virtual.', 'ADOPCION', 2, NULL, 1, 1, 'ic_mod_adopcion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (3, 'M_CONOCER_ESPECIES', 'Explorador de especies', 'Consulta la ficha de 3 especies distintas en el centro de adopción.', 'ADOPCION', 3, NULL, NULL, 2, 'ic_mod_adopcion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (4, 'M_ALIMENTAR_5', 'Buen desayuno', 'Alimenta a tu mascota 5 veces.', 'ALIMENTACION', 5, NULL, NULL, 3, 'ic_mod_alimentacion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (5, 'M_ALIMENTAR_15', 'Rutina alimenticia', 'Alimenta a tu mascota 15 veces en total.', 'ALIMENTACION', 15, NULL, 2, 4, 'ic_mod_alimentacion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (6, 'M_HIDRATAR_10', 'Agua fresca siempre', 'Da agua fresca a tu mascota 10 veces.', 'ALIMENTACION', 10, NULL, NULL, 5, 'ic_mod_alimentacion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (7, 'M_CLASIFICAR_15', 'Maestro de comidas', 'Clasifica correctamente 15 tarjetas de alimentos.', 'ALIMENTACION', 15, 2, NULL, 6, 'ic_mod_alimentacion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (8, 'M_CLASIFICAR_30', 'Nutricionista junior', 'Clasifica correctamente 30 tarjetas de alimentos.', 'ALIMENTACION', 30, NULL, 4, 7, 'ic_mod_alimentacion');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (9, 'M_HIGIENE_5', 'Pelaje brillante', 'Realiza 5 acciones de higiene.', 'HIGIENE', 5, NULL, NULL, 8, 'ic_mod_higiene');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (10, 'M_HIGIENE_10', 'Higiene experta', 'Realiza 10 acciones de higiene con tu mascota.', 'HIGIENE', 10, 3, NULL, 9, 'ic_mod_higiene');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (11, 'M_HOGAR_LIMPIO', 'Hogar impecable', 'Coloca correctamente 5 objetos de higiene o entorno en el hogar.', 'HIGIENE', 5, NULL, 3, 10, 'ic_mod_hogar');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (12, 'M_HIGIENE_20', 'Cuidador impecable', 'Realiza 20 acciones de higiene en total.', 'HIGIENE', 20, NULL, NULL, 11, 'ic_mod_higiene');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (13, 'M_JUGAR_10', 'Energía activa', 'Completa 10 actividades de juego o paseo.', 'ACTIVIDAD', 10, 4, NULL, 12, 'ic_mod_actividad');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (14, 'M_DESCANSO_5', 'Momento de siesta', 'Deja descansar a tu mascota 5 veces cuando lo necesite.', 'ACTIVIDAD', 5, NULL, NULL, 13, 'ic_mod_actividad');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (15, 'M_CARINO_10', 'Mucho cariño', 'Da cariño a tu mascota 10 veces.', 'ACTIVIDAD', 10, NULL, 6, 14, 'ic_mod_actividad');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (16, 'M_ACTIVIDAD_25', 'Compañero activo', 'Suma 25 acciones de actividad, juego o paseo en total.', 'ACTIVIDAD', 25, NULL, NULL, 15, 'ic_mod_actividad');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (17, 'M_BIENESTAR_10', 'Observador atento', 'Responde correctamente 10 escenarios de bienestar.', 'BIENESTAR', 10, 5, NULL, 16, 'ic_mod_bienestar');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (18, 'M_BIENESTAR_20', 'Veterinario junior', 'Responde correctamente 20 escenarios de bienestar en total.', 'BIENESTAR', 20, 9, NULL, 17, 'ic_mod_bienestar');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (19, 'M_BIENESTAR_5', 'Primeras señales', 'Responde correctamente 5 escenarios de bienestar.', 'BIENESTAR', 5, NULL, NULL, 18, 'ic_mod_bienestar');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (20, 'M_BIENESTAR_30', 'Experto en señales', 'Responde correctamente los 30 escenarios de bienestar disponibles.', 'BIENESTAR', 30, NULL, 5, 19, 'ic_mod_bienestar');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (21, 'M_PLAN_1', 'Mi primer plan', 'Completa tu primer plan diario de cuidado.', 'PLANIFICADOR', 1, NULL, NULL, 20, 'ic_mod_planificador');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (22, 'M_PLAN_5', 'Planificador experto', 'Completa 5 planes diarios de cuidado.', 'PLANIFICADOR', 5, 6, NULL, 21, 'ic_mod_planificador');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (23, 'M_PLAN_10', 'Rutina maestra', 'Completa 10 planes diarios de cuidado en total.', 'PLANIFICADOR', 10, NULL, 7, 22, 'ic_mod_planificador');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (24, 'M_ACADEMIA_3', 'Curioso aprendiz', 'Completa 3 lecciones de la Academia de cuidado.', 'ACADEMIA', 3, NULL, NULL, 23, 'ic_mod_academia');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (25, 'M_ACADEMIA_TODAS', 'Academia de oro', 'Completa todas las lecciones de la Academia de cuidado.', 'ACADEMIA', 8, 7, NULL, 24, 'ic_mod_academia');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (26, 'M_ACADEMIA_REPASO', 'Repasar y aprender', 'Repite 2 lecciones ya completadas para reforzar lo aprendido.', 'ACADEMIA', 2, NULL, NULL, 25, 'ic_mod_academia');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (27, 'M_SESIONES_7', 'Amigo fiel', 'Cuida a tu mascota durante 7 sesiones distintas.', 'COLECCION', 7, 8, NULL, 26, 'ic_mod_misiones');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (28, 'M_DECORAR_5', 'Decorador de hogares', 'Desbloquea 5 decoraciones distintas para el hogar.', 'COLECCION', 5, 10, NULL, 27, 'ic_mod_misiones');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (29, 'M_INSIGNIAS_5', 'Coleccionista de insignias', 'Consigue 5 insignias distintas.', 'COLECCION', 5, NULL, 8, 28, 'ic_mod_misiones');
INSERT INTO missions (id, code, title, description, type, target_count, reward_badge_id, reward_decoration_id, order_index, icon_res) VALUES (30, 'M_DECORAR_TODAS', 'Hogar completo', 'Desbloquea las 8 decoraciones disponibles.', 'COLECCION', 8, NULL, NULL, 29, 'ic_mod_misiones');
-- 9) Datos de demostración: un cuidador, su mascota y algo de progreso real
INSERT INTO user_profiles (id, alias, avatar_id, created_at, sound_enabled, haptic_enabled)
VALUES (1, 'Ana', 2, 1755600000000, 1, 1);

INSERT INTO virtual_pets (id, user_profile_id, species_id, name, avatar_variant, adopted_at,
    feeding, hydration, hygiene, activity_level, rest, affection, last_session_epoch_day, is_active)
VALUES (1, 1, 1, 'Rocky', 0, 1755600000000, 88, 76, 82, 70, 90, 95, 19985, 1);

INSERT INTO care_actions (id, virtual_pet_id, action_type, need_type, delta, timestamp) VALUES
(1, 1, 'ALIMENTAR', 'ALIMENTACION', 18, 1755600100000),
(2, 1, 'DAR_AGUA', 'HIDRATACION', 18, 1755600200000),
(3, 1, 'CEPILLAR', 'HIGIENE', 8, 1755600300000),
(4, 1, 'JUGAR', 'ACTIVIDAD', 16, 1755600400000),
(5, 1, 'DAR_CARINO', 'AFECTO', 14, 1755600500000);

INSERT INTO care_sessions (id, virtual_pet_id, started_at, ended_at, actions_count, wellbeing_at_end)
VALUES (1, 1, 1755600000000, 1755600600000, 5, 85);

INSERT INTO food_attempts (id, user_profile_id, food_item_id, virtual_pet_id, was_correct, timestamp) VALUES
(1, 1, 1, 1, 1, 1755600150000),
(2, 1, 21, 1, 1, 1755600160000);

INSERT INTO scenario_attempts (id, user_profile_id, scenario_id, virtual_pet_id, chosen_option_index, was_correct, timestamp)
VALUES (1, 1, 1, 1, 1, 1, 1755600700000);

INSERT INTO daily_care_plans (id, virtual_pet_id, date_epoch_day, completed, created_at)
VALUES (1, 1, 19985, 1, 1755600800000);
INSERT INTO daily_care_plan_items (id, daily_care_plan_id, slot, care_action_type, order_index, is_correct_placement) VALUES
(1, 1, 'MANANA', 'ALIMENTAR', 0, 1),
(2, 1, 'TARDE', 'JUGAR', 1, 1),
(3, 1, 'NOCHE', 'DEJAR_DESCANSAR', 2, 1);

INSERT INTO mission_completions (id, user_profile_id, mission_id, progress_count, completed, completed_at)
VALUES (1, 1, 1, 1, 1, 1755600050000);
INSERT INTO user_badges (id, user_profile_id, badge_id, earned_at)
VALUES (1, 1, 1, 1755600050000);

INSERT INTO academy_lesson_progress (id, user_profile_id, lesson_code, viewed_count, completed, completed_at)
VALUES (1, 1, 'L1_ALIMENTACION', 1, 1, 1755600900000);
